export const RECKON_NEXT_TU = 'RECKON_NEXT_TU';
export const CHANGE_SNAKE_DIRECTION = 'CHANGE_SNAKE_DIRECTION';
export const CHANGE_SNAKE_STATUS = 'CHANGE_SNAKE_STATUS';
export const UPDATE_BOARD = 'UPDATE_BOARD';
export const GAME_OVER = 'GAME_OVER';
