export const INCREMENT_TU = 'INCREMENT_TU';
export const UPDATE_GAME_STATUS = 'UPDATE_GAME_STATUS';

// snakes
export const CHANGE_SNAKE_DIRECTION = 'CHANGE_SNAKE_DIRECTION';
export const UPDATE_SNAKE_DATA = 'UPDATE_SNAKE_DATA';
export const RESET_SNAKE_DATA = 'RESET_SNAKE_DATA';

// board
export const AGGREGATE_BOARDS = 'AGGREGATE_BOARDS';
export const RESET_BOARD_DATA = 'RESET_BOARD_DATA';

// display board
export const GET_INITIAL_DISPLAY_BOARD = 'GET_INITIAL_DISPLAY_BOARD';
export const GET_NEXT_DISPLAY_BOARD = 'GET_NEXT_DISPLAY_BOARD';
export const RESET_DISPLAY_DATA = 'RESET_DISPLAY_DATA';

// p2p
export const P2P_GET_PEERID_FROM_URL = 'P2P_GET_PEERID_FROM_URL';
export const P2P_CONNECTION_READY = 'P2P_CONNECTION_READY';
export const P2P_UPDATE_PEER_LIST = 'P2P_UPDATE_PEER_LIST';
export const P2P_REMOVE_PEER_FROM_LIST = 'P2P_REMOVE_PEER_FROM_LIST';
