// headSets
export const UPDATE_HEAD_SETS = 'UPDATE_HEAD_SETS';
export const RESET_HEAD_SETS = 'RESET_HEAD_SETS';

// board
export const GET_INITIAL_BOARD = 'GET_INITIAL_BOARD';
export const GET_NEXT_BOARD = 'GET_NEXT_BOARD';
export const RESET_BOARD = 'RESET_BOARD';

// info
export const INCREMENT_TU = 'INCREMENT_TU';
export const SET_TU = 'SET_TU'; // for resetting and fast-forwarding
export const UPDATE_GAME_STATUS = 'UPDATE_GAME_STATUS';
export const UPDATE_STARTING_ROWS = 'UPDATE_STARTING_ROWS';
export const RESET_STARTING_ROWS = 'RESET_STARTING_ROWS';
export const UPDATE_WINNER = 'UPDATE_WINNER';
export const RESET_WINNER = 'RESET_WINNER';

// p2p
export const P2P_GET_PEERID_FROM_URL = 'P2P_GET_PEERID_FROM_URL';
export const P2P_CONNECTION_READY = 'P2P_CONNECTION_READY';
export const P2P_ADD_PEER_TO_LIST = 'P2P_ADD_PEER_TO_LIST';
export const P2P_REMOVE_PEER_FROM_LIST = 'P2P_REMOVE_PEER_FROM_LIST';
export const P2P_UPDATE_PEER_USERNAME = 'P2P_UPDATE_PEER_USERNAME';

// snakes
export const CHANGE_SNAKE_DIRECTION = 'CHANGE_SNAKE_DIRECTION';
export const CHANGE_SNAKE_STATUS = 'CHANGE_SNAKE_STATUS';
export const UPDATE_SNAKE_DATA = 'UPDATE_SNAKE_DATA';
export const RESET_SNAKE_DATA = 'RESET_SNAKE_DATA';
